## Pivots Introduction

There are Pivot tables in Excel

Pandas provides a similar function called (appropriately enough) pivot_table 

How to use the pandas pivot_table function for data analysis?

In [1]:
import pandas as pd
import numpy as np

pd.options.display.float_format = '{:,.0f}'.format
pd.options.display.max_rows = 30
pd.options.display.max_columns = 500
pd.options.display.max_colwidth = 40

In [2]:
df = pd.read_excel(io = "./Data/Investments.xlsx", sheet_name="Holdings")
display(df.tail(10))
df.dtypes

,CLIENT,ID,ISIN,Product,CCY,L1_Asset,L2_Asset,Mk_Val,Signatories
171,SAMPLE_CLIENT_B,23456789,-NA-,Cash Account,USD,Cash,Investment Cash & Cash Equivalents,"22,741",2
172,SAMPLE_CLIENT_B,23456789,-NA-,Cash Account,USD,Cash,Investment Cash & Cash Equivalents,"25,302",2
173,SAMPLE_CLIENT_B,23456789,-NA-,Cash Account,USD,Cash,Investment Cash & Cash Equivalents,"760,564",2
174,SAMPLE_CLIENT_B,23456789,-NA-,Cash Account,USD,Cash,Investment Cash & Cash Equivalents,"103,347",3
175,SAMPLE_CLIENT_B,23456789,-NA-,Cash Account,USD,Cash,Investment Cash & Cash Equivalents,"40,332",2
176,SAMPLE_CLIENT_C,34567890,-NA-,Cash Account,EUR,Cash,Investment Cash & Cash Equivalents,"27,670",4
177,SAMPLE_CLIENT_C,34567890,-NA-,Cash Account,GBP,Cash,Investment Cash & Cash Equivalents,"3,430",2
178,SAMPLE_CLIENT_C,34567890,-NA-,Cash Account,USD,Cash,Investment Cash & Cash Equivalents,"1,524,326",2
179,SAMPLE_CLIENT_C,34567890,US9127962T52,TREASURY BILL (M) 29-Oct-20,USD,Cash,Investment Cash & Cash Equivalents,"4,541,682",3
180,SAMPLE_CLIENT_C,34567890,US912796WY16,TREASURY BILL (M) 30-Jul-20,USD,Cash,Investment Cash & Cash Equivalents,"4,543,198",2

CLIENT          object
ID               int64
ISIN            object
Product         object
CCY             object
L1_Asset        object
L2_Asset        object
Mk_Val         float64
Signatories      int64
dtype: object

### Pivot the data - single Index

In [3]:
# The simplest pivot table must have a dataframe and an index. In this case, use the CLIENT column as the index.
pd.pivot_table(df, index=["CLIENT"])

                       ID    Mk_Val  Signatories
CLIENT
SAMPLE_CLIENT_A  12345678   627,892            1
SAMPLE_CLIENT_B  23456789   475,856            1
SAMPLE_CLIENT_C  34567890 1,558,792            1

### Pivot the data - Multiple Indices

In [4]:
# most of the pivot_table args can take multiple values via a list
ndx = ["CLIENT","L1_Asset", "L2_Asset"]

pd.pivot_table(df, index=ndx)

                                                                           ID  \
CLIENT          L1_Asset       L2_Asset
SAMPLE_CLIENT_A Cash           Deposits                              12345678
                               Investment Cash & Cash Equivalents    12345678
                Equities       Developed Equities                    12345678
                               Emerging Market All Cap Equities      12345678
                Fixed Income   Developed Corporate High Yield        12345678
                               Developed Corporate Investment Grade  12345678
                               Emerging Market Debt                  12345678
                Private Equity Diversified Private Equity            12345678
                Real Estate    Diversified Real Estate               12345678
SAMPLE_CLIENT_B Cash           Deposits                              23456789
                               Investment Cash & Cash Equivalents    23456789
                Equities       Developed Equities                    23456789
                               Emerging Market All Cap Equities      23456789
                Fixed Income   Developed Corporate High Yield        23456789
                               Developed Corporate Investment Grade  23456789
                               Emerging Market Debt                  23456789
                Private Equity Diversified Private Equity            23456789
                Real Estate    Diversified Real Estate               23456789
SAMPLE_CLIENT_C Cash           Deposits                              34567890
                               Investment Cash & Cash Equivalents    34567890
                Equities       Developed Equities                    34567890
                Fixed Income   Developed Corporate High Yield        34567890
                               Developed Corporate Investment Grade  34567890
                               Developed Sovereign                   34567890
                               Emerging Market Debt                  34567890
                Private Equity Diversified Private Equity            34567890

                                                                       Mk_Val  \
CLIENT          L1_Asset       L2_Asset
SAMPLE_CLIENT_A Cash           Deposits                                41,448
                               Investment Cash & Cash Equivalents     181,881
                Equities       Developed Equities                     381,250
                               Emerging Market All Cap Equities       413,287
                Fixed Income   Developed Corporate High Yield         272,245
                               Developed Corporate Investment Grade 1,143,670
                               Emerging Market Debt                   947,761
                Private Equity Diversified Private Equity             456,981
                Real Estate    Diversified Real Estate                772,538
SAMPLE_CLIENT_B Cash           Deposits                                41,144
                               Investment Cash & Cash Equivalents      81,901
                Equities       Developed Equities                      43,820
                               Emerging Market All Cap Equities        82,458
                Fixed Income   Developed Corporate High Yield       1,586,685
                               Developed Corporate Investment Grade   793,074
                               Emerging Market Debt                 1,476,551
                Private Equity Diversified Private Equity             108,879
                Real Estate    Diversified Real Estate              1,688,069
SAMPLE_CLIENT_C Cash           Deposits                                27,333
                               Investment Cash & Cash Equivalents   2,128,061
                Equities       Developed Equities                   4,303,756
                Fixed Income   Developed Corporate High Yield         544,384
                               Developed Corporate Investment Grade 1,229,318
                               Developed Sovereign                  1,734,129
                               Emerging Market Debt                   570,470
                Private Equity Diversified Private Equity           1,962,135

                                                                     Signatories
CLIENT          L1_Asset       L2_Asset
SAMPLE_CLIENT_A Cash           Deposits                                        2
                               Investment Cash & Cash Equivalents              3
                Equities       Developed Equities                              0
                               Emerging Market All Cap Equities                0
                Fixed Income   Developed Corporate High Yield                  0
                               Developed Corporate Investment Grade            0
                               Emerging Market Debt                            0
                Private Equity Diversified Private Equity                      0
                Real Estate    Diversified Real Estate                         0
SAMPLE_CLIENT_B Cash           Deposits                                        3
                               Investment Cash & Cash Equivalents              3
                Equities       Developed Equities                              0
                               Emerging Market All Cap Equities                0
                Fixed Income   Developed Corporate High Yield                  0
                               Developed Corporate Investment Grade            0
                               Emerging Market Debt                            0
                Private Equity Diversified Private Equity                      0
                Real Estate    Diversified Real Estate                         0
SAMPLE_CLIENT_C Cash           Deposits                                        2
                               Investment Cash & Cash Equivalents              3
                Equities       Developed Equities                              0
                Fixed Income   Developed Corporate High Yield                  0
                               Developed Corporate Investment Grade            0
                               Developed Sovereign                             0
                               Emerging Market Debt                            0
                Private Equity Diversified Private Equity                      0

## Aggrating and Summarizing Data

The pivot table is smart enough to start aggregating the data and summarizing it by grouping the reps with their managers.

In [5]:
# The aggfunc parameter can take a list of functions.
# E.g. using the numpy mean function and len to get a count.
ndx = ["CLIENT","L1_Asset"]
vals = ["Mk_Val"]
funcs = ['count', np.sum, np.mean, np.max, np.min]

pd.pivot_table(df, index=ndx, values=vals, aggfunc=funcs)

                                count        sum      mean      amax      amin
                               Mk_Val     Mk_Val    Mk_Val    Mk_Val    Mk_Val
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash               22  3,860,951   175,498 1,648,567       -34
                Equities           11  4,321,895   392,900 1,065,125    13,600
                Fixed Income       36 35,706,997   991,861 3,167,059   129,394
                Private Equity      5  2,284,905   456,981 1,600,344    20,888
                Real Estate         2  1,545,076   772,538   965,454   579,622
SAMPLE_CLIENT_B Cash               24  1,843,343    76,806   760,564       162
                Equities           23  1,046,507    45,500   179,730    10,366
                Fixed Income       30 30,737,123 1,024,571 4,606,631    15,213
                Private Equity      5    544,396   108,879   220,373    50,603
                Real Estate         4  6,752,277 1,688,069 3,488,105    58,884
SAMPLE_CLIENT_C Cash                6 10,667,640 1,777,940 4,543,198     3,430
                Equities            1  4,303,756 4,303,756 4,303,756 4,303,756
                Fixed Income       11 12,683,526 1,153,048 1,770,178   530,352
                Private Equity      1  1,962,135 1,962,135 1,962,135 1,962,135

### Columns vs. Values
Columns are optional - they provide an additional way to segment the actual values you care about. 

The aggregation functions are applied to the values you list.

In [6]:
ndx = ["CLIENT","L1_Asset"]
vals = ["Mk_Val"]
funcs = ['count', np.sum,np.mean, np.max, np.min]
cols = ['CCY']

pd.pivot_table(df,index=ndx,values=vals, aggfunc=funcs, columns = cols, fill_value=0)

                                count                     sum            \
                               Mk_Val                  Mk_Val
CCY                               CHF EUR GBP USD XAU     CHF       EUR
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                0   3   7  11   1       0     9,377
                Equities            0   0   0  11   0       0         0
                Fixed Income        0   1   0  35   0       0   129,394
                Private Equity      0   0   0   5   0       0         0
                Real Estate         0   0   0   2   0       0         0
SAMPLE_CLIENT_B Cash                4   4   6  10   0 169,412   172,872
                Equities            4   5   1  13   0 148,240   114,968
                Fixed Income        0   5   0  25   0       0 6,654,878
                Private Equity      0   0   0   5   0       0         0
                Real Estate         0   0   0   4   0       0         0
SAMPLE_CLIENT_C Cash                0   1   1   4   0       0    27,670
                Equities            0   0   1   0   0       0         0
                Fixed Income        0   0   0  11   0       0         0
                Private Equity      0   1   0   0   0       0 1,962,135

                                                             mean            \
                                                           Mk_Val
CCY                                  GBP        USD    XAU    CHF       EUR
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash             134,903  3,618,179 98,491      0     3,126
                Equities               0  4,321,895      0      0         0
                Fixed Income           0 35,577,604      0      0   129,394
                Private Equity         0  2,284,905      0      0         0
                Real Estate            0  1,545,076      0      0         0
SAMPLE_CLIENT_B Cash             114,348  1,386,711      0 42,353    43,218
                Equities          20,826    762,473      0 37,060    22,994
                Fixed Income           0 24,082,245      0      0 1,330,976
                Private Equity         0    544,396      0      0         0
                Real Estate            0  6,752,277      0      0         0
SAMPLE_CLIENT_C Cash               3,430 10,636,540      0      0    27,670
                Equities       4,303,756          0      0      0         0
                Fixed Income           0 12,683,526      0      0         0
                Private Equity         0          0      0      0 1,962,135

                                                             amax            \
                                                           Mk_Val
CCY                                  GBP       USD    XAU     CHF       EUR
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash              19,272   328,925 98,491       0     6,560
                Equities               0   392,900      0       0         0
                Fixed Income           0 1,016,503      0       0   129,394
                Private Equity         0   456,981      0       0         0
                Real Estate            0   772,538      0       0         0
SAMPLE_CLIENT_B Cash              19,058   138,671      0 148,360    71,869
                Equities          20,826    58,652      0  91,204    29,986
                Fixed Income           0   963,290      0       0 3,194,866
                Private Equity         0   108,879      0       0         0
                Real Estate            0 1,688,069      0       0         0
SAMPLE_CLIENT_C Cash               3,430 2,659,135      0       0    27,670
                Equities       4,303,756         0      0       0         0
                Fixed Income           0 1,153,048      0       0         0
                Private Equity         0         0      0       0 1,962,135

                                                            amin            \
                                                          Mk_Val
CCY                                  GBP       USD    XAU    CHF       EUR
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash              84,191 1,648,567 98,491      0         9
                Equities               0 1,065,125      0      0         0
                Fixed Income           0 3,167,059      0      0   129,394
                Private Equity         0 1,600,344      0      0         0
                Real Estate            0   965,454      0      0         0
SAMPLE_CLIENT_B Cash              62,875   760,564      0    162     4,833
                Equities          20,826   179,730      0 14,873    17,868
                Fixed Income           0 4,606,631      0      0   307,007
                Private Equity         0   220,373      0      0         0
                Real Estate            0 3,488,105      0      0         0
SAMPLE_CLIENT_C Cash               3,430 4,543,198      0      0    27,670
                Equities       4,303,756         0      0      0         0
                Fixed Income           0 1,770,178      0      0         0
                Private Equity         0         0      0      0 1,962,135



CCY                                  GBP     USD    XAU
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                 -34       5 98,491
                Equities               0  13,600      0
                Fixed Income           0 149,460      0
                Private Equity         0  20,888      0
                Real Estate            0 579,622      0
SAMPLE_CLIENT_B Cash                 521   5,516      0
                Equities          20,826  10,366      0
                Fixed Income           0  15,213      0
                Private Equity         0  50,603      0
                Real Estate            0  58,884      0
SAMPLE_CLIENT_C Cash               3,430  27,333      0
                Equities       4,303,756       0      0
                Fixed Income           0 530,352      0
                Private Equity         0       0      0

In [7]:
# Add Asset Class L2 to the colums list
ndx = ["CLIENT","L1_Asset"]
vals = ["Mk_Val"]
funcs = [np.sum]
cols = ['CCY', 'L2_Asset']

pd.pivot_table(df,index=ndx,values=vals, aggfunc=funcs, columns = cols, fill_value=0)

                                              sum  \
                                           Mk_Val
CCY                                           CHF
L2_Asset                       Developed Equities
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                            0
                Equities                        0
                Fixed Income                    0
                Private Equity                  0
                Real Estate                     0
SAMPLE_CLIENT_B Cash                            0
                Equities                  148,240
                Fixed Income                    0
                Private Equity                  0
                Real Estate                     0
SAMPLE_CLIENT_C Cash                            0
                Equities                        0
                Fixed Income                    0
                Private Equity                  0

                                                                   \

CCY
L2_Asset                       Investment Cash & Cash Equivalents
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                            0
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0
                Real Estate                                     0
SAMPLE_CLIENT_B Cash                                      169,412
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0
                Real Estate                                     0
SAMPLE_CLIENT_C Cash                                            0
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0

                                                               \

CCY                                                       EUR
L2_Asset                       Developed Corporate High Yield
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                        0
                Equities                                    0
                Fixed Income                                0
                Private Equity                              0
                Real Estate                                 0
SAMPLE_CLIENT_B Cash                                        0
                Equities                                    0
                Fixed Income                        1,586,685
                Private Equity                              0
                Real Estate                                 0
SAMPLE_CLIENT_C Cash                                        0
                Equities                                    0
                Fixed Income                                0
                Private Equity                              0

                                                                     \

CCY
L2_Asset                       Developed Corporate Investment Grade
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                              0
                Equities                                          0
                Fixed Income                                      0
                Private Equity                                    0
                Real Estate                                       0
SAMPLE_CLIENT_B Cash                                              0
                Equities                                          0
                Fixed Income                              4,106,182
                Private Equity                                    0
                Real Estate                                       0
SAMPLE_CLIENT_C Cash                                              0
                Equities                                          0
                Fixed Income                                      0
                Private Equity                                    0

                                                                              \

CCY
L2_Asset                       Developed Equities Diversified Private Equity
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                            0                          0
                Equities                        0                          0
                Fixed Income                    0                          0
                Private Equity                  0                          0
                Real Estate                     0                          0
SAMPLE_CLIENT_B Cash                            0                          0
                Equities                  114,968                          0
                Fixed Income                    0                          0
                Private Equity                  0                          0
                Real Estate                     0                          0
SAMPLE_CLIENT_C Cash                            0                          0
                Equities                        0                          0
                Fixed Income                    0                          0
                Private Equity                  0                  1,962,135

                                                     \

CCY
L2_Asset                       Emerging Market Debt
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                              0
                Equities                          0
                Fixed Income                129,394
                Private Equity                    0
                Real Estate                       0
SAMPLE_CLIENT_B Cash                              0
                Equities                          0
                Fixed Income                962,010
                Private Equity                    0
                Real Estate                       0
SAMPLE_CLIENT_C Cash                              0
                Equities                          0
                Fixed Income                      0
                Private Equity                    0

                                                                   \

CCY
L2_Asset                       Investment Cash & Cash Equivalents
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                        9,377
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0
                Real Estate                                     0
SAMPLE_CLIENT_B Cash                                      172,872
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0
                Real Estate                                     0
SAMPLE_CLIENT_C Cash                                       27,670
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0

                                                   \

CCY                                           GBP
L2_Asset                       Developed Equities
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                            0
                Equities                        0
                Fixed Income                    0
                Private Equity                  0
                Real Estate                     0
SAMPLE_CLIENT_B Cash                            0
                Equities                   20,826
                Fixed Income                    0
                Private Equity                  0
                Real Estate                     0
SAMPLE_CLIENT_C Cash                            0
                Equities                4,303,756
                Fixed Income                    0
                Private Equity                  0

                                                                            \

CCY                                                                    USD
L2_Asset                       Investment Cash & Cash Equivalents Deposits
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                      134,903   41,448
                Equities                                        0        0
                Fixed Income                                    0        0
                Private Equity                                  0        0
                Real Estate                                     0        0
SAMPLE_CLIENT_B Cash                                      114,348  123,431
                Equities                                        0        0
                Fixed Income                                    0        0
                Private Equity                                  0        0
                Real Estate                                     0        0
SAMPLE_CLIENT_C Cash                                        3,430   27,333
                Equities                                        0        0
                Fixed Income                                    0        0
                Private Equity                                  0        0

                                                               \

CCY
L2_Asset                       Developed Corporate High Yield
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                        0
                Equities                                    0
                Fixed Income                          544,490
                Private Equity                              0
                Real Estate                                 0
SAMPLE_CLIENT_B Cash                                        0
                Equities                                    0
                Fixed Income                                0
                Private Equity                              0
                Real Estate                                 0
SAMPLE_CLIENT_C Cash                                        0
                Equities                                    0
                Fixed Income                          544,384
                Private Equity                              0

                                                                     \

CCY
L2_Asset                       Developed Corporate Investment Grade
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                              0
                Equities                                          0
                Fixed Income                             17,155,043
                Private Equity                                    0
                Real Estate                                       0
SAMPLE_CLIENT_B Cash                                              0
                Equities                                          0
                Fixed Income                             11,755,299
                Private Equity                                    0
                Real Estate                                       0
SAMPLE_CLIENT_C Cash                                              0
                Equities                                          0
                Fixed Income                              9,834,544
                Private Equity                                    0

                                                                       \

CCY
L2_Asset                       Developed Equities Developed Sovereign
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                            0                   0
                Equities                2,668,747                   0
                Fixed Income                    0                   0
                Private Equity                  0                   0
                Real Estate                     0                   0
SAMPLE_CLIENT_B Cash                            0                   0
                Equities                  680,015                   0
                Fixed Income                    0                   0
                Private Equity                  0                   0
                Real Estate                     0                   0
SAMPLE_CLIENT_C Cash                            0                   0
                Equities                        0                   0
                Fixed Income                    0           1,734,129
                Private Equity                  0                   0

                                                           \

CCY
L2_Asset                       Diversified Private Equity
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                    0
                Equities                                0
                Fixed Income                            0
                Private Equity                  2,284,905
                Real Estate                             0
SAMPLE_CLIENT_B Cash                                    0
                Equities                                0
                Fixed Income                            0
                Private Equity                    544,396
                Real Estate                             0
SAMPLE_CLIENT_C Cash                                    0
                Equities                                0
                Fixed Income                            0
                Private Equity                          0

                                                        \

CCY
L2_Asset                       Diversified Real Estate
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                 0
                Equities                             0
                Fixed Income                         0
                Private Equity                       0
                Real Estate                  1,545,076
SAMPLE_CLIENT_B Cash                                 0
                Equities                             0
                Fixed Income                         0
                Private Equity                       0
                Real Estate                  6,752,277
SAMPLE_CLIENT_C Cash                                 0
                Equities                             0
                Fixed Income                         0
                Private Equity                       0

                                                                 \

CCY
L2_Asset                       Emerging Market All Cap Equities
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                          0
                Equities                              1,653,148
                Fixed Income                                  0
                Private Equity                                0
                Real Estate                                   0
SAMPLE_CLIENT_B Cash                                          0
                Equities                                 82,458
                Fixed Income                                  0
                Private Equity                                0
                Real Estate                                   0
SAMPLE_CLIENT_C Cash                                          0
                Equities                                      0
                Fixed Income                                  0
                Private Equity                                0

                                                     \

CCY
L2_Asset                       Emerging Market Debt
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                              0
                Equities                          0
                Fixed Income             17,878,071
                Private Equity                    0
                Real Estate                       0
SAMPLE_CLIENT_B Cash                              0
                Equities                          0
                Fixed Income             12,326,947
                Private Equity                    0
                Real Estate                       0
SAMPLE_CLIENT_C Cash                              0
                Equities                          0
                Fixed Income                570,470
                Private Equity                    0

                                                                   \

CCY
L2_Asset                       Investment Cash & Cash Equivalents
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                    3,576,732
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0
                Real Estate                                     0
SAMPLE_CLIENT_B Cash                                    1,263,280
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0
                Real Estate                                     0
SAMPLE_CLIENT_C Cash                                   10,609,207
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0



CCY                                                           XAU
L2_Asset                       Investment Cash & Cash Equivalents
CLIENT          L1_Asset
SAMPLE_CLIENT_A Cash                                       98,491
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0
                Real Estate                                     0
SAMPLE_CLIENT_B Cash                                            0
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0
                Real Estate                                     0
SAMPLE_CLIENT_C Cash                                            0
                Equities                                        0
                Fixed Income                                    0
                Private Equity                                  0

In [8]:
# Add Asset Class L2 to the index list
ndx = ["CLIENT","L1_Asset", "L2_Asset"]
vals = ["Mk_Val"]
funcs = [np.sum]
cols = ['CCY']

table = pd.pivot_table(df,index=ndx,values=vals, aggfunc=funcs, columns = cols, fill_value=0)

table

                                                                        sum  \
                                                                     Mk_Val
CCY                                                                     CHF
CLIENT          L1_Asset       L2_Asset
SAMPLE_CLIENT_A Cash           Deposits                                   0
                               Investment Cash & Cash Equivalents         0
                Equities       Developed Equities                         0
                               Emerging Market All Cap Equities           0
                Fixed Income   Developed Corporate High Yield             0
                               Developed Corporate Investment Grade       0
                               Emerging Market Debt                       0
                Private Equity Diversified Private Equity                 0
                Real Estate    Diversified Real Estate                    0
SAMPLE_CLIENT_B Cash           Deposits                                   0
                               Investment Cash & Cash Equivalents   169,412
                Equities       Developed Equities                   148,240
                               Emerging Market All Cap Equities           0
                Fixed Income   Developed Corporate High Yield             0
                               Developed Corporate Investment Grade       0
                               Emerging Market Debt                       0
                Private Equity Diversified Private Equity                 0
                Real Estate    Diversified Real Estate                    0
SAMPLE_CLIENT_C Cash           Deposits                                   0
                               Investment Cash & Cash Equivalents         0
                Equities       Developed Equities                         0
                Fixed Income   Developed Corporate High Yield             0
                               Developed Corporate Investment Grade       0
                               Developed Sovereign                        0
                               Emerging Market Debt                       0
                Private Equity Diversified Private Equity                 0

                                                                               \

CCY                                                                       EUR
CLIENT          L1_Asset       L2_Asset
SAMPLE_CLIENT_A Cash           Deposits                                     0
                               Investment Cash & Cash Equivalents       9,377
                Equities       Developed Equities                           0
                               Emerging Market All Cap Equities             0
                Fixed Income   Developed Corporate High Yield               0
                               Developed Corporate Investment Grade         0
                               Emerging Market Debt                   129,394
                Private Equity Diversified Private Equity                   0
                Real Estate    Diversified Real Estate                      0
SAMPLE_CLIENT_B Cash           Deposits                                     0
                               Investment Cash & Cash Equivalents     172,872
                Equities       Developed Equities                     114,968
                               Emerging Market All Cap Equities             0
                Fixed Income   Developed Corporate High Yield       1,586,685
                               Developed Corporate Investment Grade 4,106,182
                               Emerging Market Debt                   962,010
                Private Equity Diversified Private Equity                   0
                Real Estate    Diversified Real Estate                      0
SAMPLE_CLIENT_C Cash           Deposits                                     0
                               Investment Cash & Cash Equivalents      27,670
                Equities       Developed Equities                           0
                Fixed Income   Developed Corporate High Yield               0
                               Developed Corporate Investment Grade         0
                               Developed Sovereign                          0
                               Emerging Market Debt                         0
                Private Equity Diversified Private Equity           1,962,135

                                                                               \

CCY                                                                       GBP
CLIENT          L1_Asset       L2_Asset
SAMPLE_CLIENT_A Cash           Deposits                                     0
                               Investment Cash & Cash Equivalents     134,903
                Equities       Developed Equities                           0
                               Emerging Market All Cap Equities             0
                Fixed Income   Developed Corporate High Yield               0
                               Developed Corporate Investment Grade         0
                               Emerging Market Debt                         0
                Private Equity Diversified Private Equity                   0
                Real Estate    Diversified Real Estate                      0
SAMPLE_CLIENT_B Cash           Deposits                                     0
                               Investment Cash & Cash Equivalents     114,348
                Equities       Developed Equities                      20,826
                               Emerging Market All Cap Equities             0
                Fixed Income   Developed Corporate High Yield               0
                               Developed Corporate Investment Grade         0
                               Emerging Market Debt                         0
                Private Equity Diversified Private Equity                   0
                Real Estate    Diversified Real Estate                      0
SAMPLE_CLIENT_C Cash           Deposits                                     0
                               Investment Cash & Cash Equivalents       3,430
                Equities       Developed Equities                   4,303,756
                Fixed Income   Developed Corporate High Yield               0
                               Developed Corporate Investment Grade         0
                               Developed Sovereign                          0
                               Emerging Market Debt                         0
                Private Equity Diversified Private Equity                   0

                                                                                \

CCY                                                                        USD
CLIENT          L1_Asset       L2_Asset
SAMPLE_CLIENT_A Cash           Deposits                                 41,448
                               Investment Cash & Cash Equivalents    3,576,732
                Equities       Developed Equities                    2,668,747
                               Emerging Market All Cap Equities      1,653,148
                Fixed Income   Developed Corporate High Yield          544,490
                               Developed Corporate Investment Grade 17,155,043
                               Emerging Market Debt                 17,878,071
                Private Equity Diversified Private Equity            2,284,905
                Real Estate    Diversified Real Estate               1,545,076
SAMPLE_CLIENT_B Cash           Deposits                                123,431
                               Investment Cash & Cash Equivalents    1,263,280
                Equities       Developed Equities                      680,015
                               Emerging Market All Cap Equities         82,458
                Fixed Income   Developed Corporate High Yield                0
                               Developed Corporate Investment Grade 11,755,299
                               Emerging Market Debt                 12,326,947
                Private Equity Diversified Private Equity              544,396
                Real Estate    Diversified Real Estate               6,752,277
SAMPLE_CLIENT_C Cash           Deposits                                 27,333
                               Investment Cash & Cash Equivalents   10,609,207
                Equities       Developed Equities                            0
                Fixed Income   Developed Corporate High Yield          544,384
                               Developed Corporate Investment Grade  9,834,544
                               Developed Sovereign                   1,734,129
                               Emerging Market Debt                    570,470
                Private Equity Diversified Private Equity                    0



CCY                                                                    XAU
CLIENT          L1_Asset       L2_Asset
SAMPLE_CLIENT_A Cash           Deposits                                  0
                               Investment Cash & Cash Equivalents   98,491
                Equities       Developed Equities                        0
                               Emerging Market All Cap Equities          0
                Fixed Income   Developed Corporate High Yield            0
                               Developed Corporate Investment Grade      0
                               Emerging Market Debt                      0
                Private Equity Diversified Private Equity                0
                Real Estate    Diversified Real Estate                   0
SAMPLE_CLIENT_B Cash           Deposits                                  0
                               Investment Cash & Cash Equivalents        0
                Equities       Developed Equities                        0
                               Emerging Market All Cap Equities          0
                Fixed Income   Developed Corporate High Yield            0
                               Developed Corporate Investment Grade      0
                               Emerging Market Debt                      0
                Private Equity Diversified Private Equity                0
                Real Estate    Diversified Real Estate                   0
SAMPLE_CLIENT_C Cash           Deposits                                  0
                               Investment Cash & Cash Equivalents        0
                Equities       Developed Equities                        0
                Fixed Income   Developed Corporate High Yield            0
                               Developed Corporate Investment Grade      0
                               Developed Sovereign                       0
                               Emerging Market Debt                      0
                Private Equity Diversified Private Equity                0

### Add some colour

In [9]:
# High low colours
fmts = { col:'{:,.0f}'.format for col in table.columns }

table.style.format(fmts).highlight_max(color='lightgreen').highlight_min(color='red')

In [10]:
# Gradient Colours
table.style.format(fmts).background_gradient(cmap='Blues')